"""initial schema

Revision ID: 9e333fe72908
Revises: 
Create Date: 2026-09-02 11:15:12.534144
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9e333fe72908'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality', sa.String(length=60), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('collectors_supported', sa.Integer(), nullable=False),
    sa.Column('formal_transitions', sa.Integer(), nullable=False),
    sa.Column('insured_workers', sa.Integer(), nullable=False),
    sa.Column('insured_days', sa.Integer(), nullable=False),
    sa.Column('funding_allocated_try', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collector_programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collector_programs_municipality'), ['municipality'], unique=False)
        batch_op.create_index(batch_op.f('ix_collector_programs_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_collector_programs_region'), ['region'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=180), nullable=False),
    sa.Column('tax_identifier', sa.String(length=16), nullable=False),
    sa.Column('sector', sa.String(length=40), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('company_size', sa.String(length=12), nullable=False),
    sa.Column('registry_status', sa.String(length=20), nullable=False),
    sa.Column('has_production_data', sa.Boolean(), nullable=False),
    sa.Column('has_import_data', sa.Boolean(), nullable=False),
    sa.Column('has_gtip_data', sa.Boolean(), nullable=False),
    sa.Column('has_field_data', sa.Boolean(), nullable=False),
    sa.Column('gtip_coverage', sa.Float(), nullable=False),
    sa.Column('last_data_update', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_company_size'), ['company_size'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_tax_identifier'), ['tax_identifier'], unique=True)

    op.create_table('pilot_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('sector', sa.String(length=40), nullable=True),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('shortlist_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('companies_analysed', sa.Integer(), nullable=False),
    sa.Column('companies_shortlisted', sa.Integer(), nullable=False),
    sa.Column('simulate_outcomes', sa.Boolean(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('previous_status', sa.String(length=28), nullable=True),
    sa.Column('new_status', sa.String(length=28), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decision_id', sa.String(length=40), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_current_hash'), ['current_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_sequence'), ['sequence'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)

    op.create_table('audit_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=28), nullable=False),
    sa.Column('auditor_id', sa.String(length=60), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decision_id', sa.String(length=40), nullable=False),
    sa.Column('confirmed_additional_tonnage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_reviews_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_reviews_decision_id'), ['decision_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_reviews_status'), ['status'], unique=False)

    op.create_table('declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('declared_packaging_tonnage', sa.Float(), nullable=True),
    sa.Column('production_volume', sa.Float(), nullable=True),
    sa.Column('import_volume', sa.Float(), nullable=True),
    sa.Column('export_volume', sa.Float(), nullable=True),
    sa.Column('material_breakdown', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period', name='uq_declaration_period')
    )
    with op.batch_alter_table('declarations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_declarations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_declarations_period'), ['period'], unique=False)

    op.create_table('field_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('observed_packaging_tonnage', sa.Float(), nullable=False),
    sa.Column('observation', sa.String(length=400), nullable=False),
    sa.Column('inspector', sa.String(length=80), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_observations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_observations_period'), ['period'], unique=False)

    op.create_table('gtip_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('gtip_code', sa.String(length=12), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.Column('quantity_tonnes', sa.Float(), nullable=False),
    sa.Column('packaging_coefficient', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gtip_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gtip_lines_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gtip_lines_period'), ['period'], unique=False)

    op.create_table('score_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_level', sa.String(length=12), nullable=False),
    sa.Column('declared_tonnage', sa.Float(), nullable=True),
    sa.Column('expected_lower_bound', sa.Float(), nullable=False),
    sa.Column('expected_median', sa.Float(), nullable=False),
    sa.Column('expected_upper_bound', sa.Float(), nullable=False),
    sa.Column('position', sa.String(length=12), nullable=False),
    sa.Column('shortfall_tonnage', sa.Float(), nullable=False),
    sa.Column('estimated_gekap_gap_try', sa.Float(), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=False),
    sa.Column('signal_coverage', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=12), nullable=False),
    sa.Column('scoring_engine', sa.String(length=24), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period', name='uq_score_period')
    )
    with op.batch_alter_table('score_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_results_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_results_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_results_priority_level'), ['priority_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_results_priority_score'), ['priority_score'], unique=False)

    op.create_table('signal_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_result_id', sa.Integer(), nullable=False),
    sa.Column('signal_code', sa.String(length=4), nullable=False),
    sa.Column('signal_key', sa.String(length=40), nullable=False),
    sa.Column('signal_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('missing_data_reason', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['score_result_id'], ['score_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_results_score_result_id'), ['score_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_results_signal_code'), ['signal_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_results_signal_code'))
        batch_op.drop_index(batch_op.f('ix_signal_results_score_result_id'))

    op.drop_table('signal_results')
    with op.batch_alter_table('score_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_results_priority_score'))
        batch_op.drop_index(batch_op.f('ix_score_results_priority_level'))
        batch_op.drop_index(batch_op.f('ix_score_results_period'))
        batch_op.drop_index(batch_op.f('ix_score_results_company_id'))

    op.drop_table('score_results')
    with op.batch_alter_table('gtip_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gtip_lines_period'))
        batch_op.drop_index(batch_op.f('ix_gtip_lines_company_id'))

    op.drop_table('gtip_lines')
    with op.batch_alter_table('field_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_observations_period'))
        batch_op.drop_index(batch_op.f('ix_field_observations_company_id'))

    op.drop_table('field_observations')
    with op.batch_alter_table('declarations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_declarations_period'))
        batch_op.drop_index(batch_op.f('ix_declarations_company_id'))

    op.drop_table('declarations')
    with op.batch_alter_table('audit_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_reviews_status'))
        batch_op.drop_index(batch_op.f('ix_audit_reviews_decision_id'))
        batch_op.drop_index(batch_op.f('ix_audit_reviews_company_id'))

    op.drop_table('audit_reviews')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_sequence'))
        batch_op.drop_index(batch_op.f('ix_audit_events_decision_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_current_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_company_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    op.drop_table('pilot_runs')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_tax_identifier'))
        batch_op.drop_index(batch_op.f('ix_companies_sector'))
        batch_op.drop_index(batch_op.f('ix_companies_region'))
        batch_op.drop_index(batch_op.f('ix_companies_company_size'))
        batch_op.drop_index(batch_op.f('ix_companies_company_name'))

    op.drop_table('companies')
    with op.batch_alter_table('collector_programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collector_programs_region'))
        batch_op.drop_index(batch_op.f('ix_collector_programs_period'))
        batch_op.drop_index(batch_op.f('ix_collector_programs_municipality'))

    op.drop_table('collector_programs')
    # ### end Alembic commands ###
