/**
 * Every fixed string the interface writes for itself.
 *
 * Keys are grouped by where they appear. Anything that varies with the data —
 * a company name, a province, a figure — is a `{placeholder}` filled at call
 * time, so word order can differ between the two languages.
 *
 * The domain's own vocabulary (priority levels, workflow statuses, sector and
 * material names, the eight checks) lives in format.js next to the tone maps
 * it is always used with.
 */

export const STRINGS = {
  // ------------------------------------------------------------------ en --
  en: {
    'lang.switch': 'Language',
    'lang.en': 'English',
    'lang.tr': 'Turkish',

    'brand.sub': 'Inspection prioritisation',

    'key.button': 'API key',
    'key.set': 'Key in use',
    'key.title': 'Decisions need an API key',
    'key.note':
      'Decisions, rescoring and pilot runs are signed with this key. It stays in this tab only and is cleared when the tab closes.',
    'key.placeholder': 'Paste your X-API-Key',
    'key.save': 'Use key',
    'key.clear': 'Forget key',
    'key.saved': 'Key saved for this tab.',
    'key.cleared': 'Key removed.',

    'nav.overview': 'Overview',
    'nav.queue': 'Inspection queue',
    'nav.quality': 'Data quality',
    'nav.impact': 'Climate impact',
    'nav.pilot': 'Antalya pilot',
    'nav.trail': 'Audit trail',
    'nav.transparency': 'How this works',
    'nav.lightMode': 'Light mode',
    'nav.darkMode': 'Dark mode',
    'nav.switchTheme': 'Switch theme',

    'notFound.title': 'No such page',
    'notFound.note': 'The address does not match anything in the platform.',
    'notFound.back': 'Back to overview',

    'state.errorTitle': 'The service did not answer',
    'state.errorNote': 'Check that the API is running, then try again.',
    'state.retry': 'Try again',
    'state.loading': 'Loading',

    'common.close': 'Close',
    'common.cancel': 'Cancel',
    'common.previous': 'Previous',
    'common.next': 'Next',
    'common.newer': 'Newer',
    'common.older': 'Older',
    'common.clear': 'Clear',
    'common.detail': 'Detail',
    'common.notReported': 'Not reported',
    'common.on': 'On',
    'common.off': 'Off',
    'common.of': 'of',
    'common.company': 'Company',
    'common.sector': 'Sector',
    'common.region': 'Region',
    'common.priority': 'Priority',
    'common.status': 'Status',
    'common.material': 'Material',
    'common.tonnage': 'Tonnage',
    'common.period': 'Period',
    'common.production': 'Production',
    'common.imports': 'Imports',
    'common.declared': 'Declared',
    'common.check': 'Check',
    'common.system': 'System',
    'common.range': '{from} to {to}',

    // Overview -------------------------------------------------------------
    'overview.eyebrow': 'Period {period}',
    'overview.title': 'Overview',
    'overview.rescore': 'Re-run scoring',
    'overview.scoring': 'Scoring',
    'overview.rescored': '{count} companies rescored in {ms} ms',
    'overview.spread': 'Priority spread',
    'overview.openQueue': 'Open queue',
    'overview.scoredAcross': 'companies scored across {regions} provinces and {sectors} sectors',
    'overview.awaiting': 'Awaiting a decision',
    'overview.awaitingNote': '{progress} in progress, {closed} closed',
    'overview.noFiling': 'No filing on record',
    'overview.noFilingNote': 'Output is known, a declaration is not',
    'overview.exposure': 'Exposure',
    'overview.tonnageIdentified': 'Tonnage identified',
    'overview.tonnageIdentifiedNote': 'Below the expected range, at high and critical priority',
    'overview.atStake': 'Contribution at stake',
    'overview.atStakeNote': '2026 tariff applied to the unexplained tonnage',
    'overview.concentration': 'Concentration',
    'overview.concentrationNote': 'of that sits in the top 50 companies, worth {value}',
    'overview.queue': 'Priority queue',
    'overview.allCompanies': 'All {count} companies',
    'overview.coverage': 'Coverage',
    'overview.fieldCoverage': 'Field coverage',
    'overview.coverageBreakdown': '{available} complete, {partial} partial, {missing} missing',
    'overview.signalsEvaluated': 'Signals evaluated',
    'overview.firing': '{count} firing',
    'overview.heldOut':
      'A check that cannot run is held out of the calculation, never counted as a check that passed.',
    'overview.workflow': 'Workflow',

    // Queue ----------------------------------------------------------------
    'queue.eyebrow': 'Operations',
    'queue.title': 'Inspection queue',
    'queue.search': 'Company name or tax number',
    'queue.searchLabel': 'Search companies',
    'queue.allPriorities': 'All priorities',
    'queue.allSectors': 'All sectors',
    'queue.allProvinces': 'All provinces',
    'queue.anySize': 'Any size',
    'queue.anyStatus': 'Any status',
    'queue.anyEvidence': 'Any evidence level',
    'queue.sortOrder': 'Sort order',
    'queue.sortBy': 'Sort by {what}',
    'queue.sort.priority': 'priority score',
    'queue.sort.gap': 'contribution at stake',
    'queue.sort.shortfall': 'unexplained tonnage',
    'queue.sort.quality': 'data quality',
    'queue.sort.name': 'company name',
    'queue.evidence.HIGH': 'Well evidenced',
    'queue.evidence.MEDIUM': 'Partly evidenced',
    'queue.evidence.LOW': 'Thin evidence',
    'queue.noMatch': 'No companies match',
    'queue.pageRange': '{from} to {to} of {total}',
    'queue.pageTotals': '{tonnes} and {value} unexplained on this page',

    // The queue table ------------------------------------------------------
    'table.leadingReason': 'Leading reason',
    'table.data': 'Data',
    'table.action': 'Action',
    'table.contributionShare': '{percent}% of the score',
    'table.noConcern': 'No check raised a concern',
    'table.atStake': '{value} at stake',
    'table.emptyTitle': 'Nothing matches those filters',
    'table.emptyNote': 'Widen the selection, or clear it to see the whole period.',

    'action.flag': 'Mark for inspection',
    'action.flagTitle': 'Mark for inspection — adds the company to the field schedule',
    'action.flagOn': 'Already marked for inspection',
    'action.flagDone': '{company} is on the field schedule',
    'action.clear': 'Clear',
    'action.clearTitle':
      'Clear — accepts the declaration and takes the company out of the queue',
    'action.clearOn': 'Already cleared, no action required',
    'action.clearDone': '{company} is out of the queue',
    'action.note': '{action} from the inspection queue.',
    'action.for': '{action}: {company}',

    // Company --------------------------------------------------------------
    'company.backToQueue': 'Inspection queue',
    'company.rank': 'Rank {rank} of {total}',
    'company.history': 'History',
    'company.record': 'Record decision',
    'company.noResultTitle': 'No result for {period}',
    'company.noResultNote': 'The company has no scored record in this period.',
    'company.priority': 'Inspection priority',
    'company.result': 'Result',
    'company.evidenceBase': 'Evidence base',
    'company.checksRan': 'Checks that ran',
    'company.checksFiring': 'Checks firing',
    'company.scoredAt': 'Scored',
    'company.engine': 'Engine',
    'company.policy': 'Policy',
    'company.declarationFor': 'Declaration for {period}',
    'company.exports': 'Exports',
    'company.packagingDeclared': 'Packaging declared',
    'company.materialSplit': 'Material split as declared',
    'company.declaredAgainst': 'Declared against expected',
    'company.whyPrioritised': 'Why this company is prioritised',
    'company.allChecks': 'All eight checks',
    'company.evidenceHeld': 'Evidence held on this company',
    'company.dataQuality': 'Data quality {percent}',
    'company.lastUpdated': 'Last updated {when}.',
    'company.missingFields': ' Missing: {fields}.',
    'company.peerGroup': 'Peer group',
    'company.cohort': 'Cohort',
    'company.companiesFiled': 'Companies that filed',
    'company.thisCompany': 'This company',
    'company.cohortMedian': 'Cohort median',
    'company.siteVisits': 'Site visits',
    'company.noVisit': 'No visit has been recorded, so the field check could not be evaluated.',
    'company.measuredOnSite': '{amount} measured on site',
    'company.measured': '{amount} measured',
    'company.customsLines': 'Customs lines matched to this period',
    'company.gtip': 'GTIP',
    'company.description': 'Description',
    'company.quantity': 'Quantity',
    'company.packagingPerTonne': 'Packaging per tonne',
    'company.impliedPackaging': 'Implied packaging',
    'company.recordedAs': 'Recorded as {status}',

    // Score and range ------------------------------------------------------
    'score.priority': '{level} priority',
    'score.thinEvidence': 'Ranked on a thin evidence base. Treat the position as provisional.',
    'score.forReview': 'Ranked for human review, not judged.',
    'score.evidenceCoverage': 'Evidence coverage',
    'score.dataQuality': 'Data quality',
    'range.declared': 'Declared',
    'range.expectedRange': 'Expected range',
    'range.expectedMedian': 'Expected median',
    'range.unexplained': 'Unexplained',
    'range.atStake': 'Contribution at stake',
    'range.declaredTitle': '{amount} declared',
    'range.shortfallNote':
      '. The shortfall is measured against the bottom of the range, not its middle.',

    // Signals --------------------------------------------------------------
    'signals.quietTitle': 'No check raised a concern',
    'signals.quietNote': 'Every signal that could be evaluated came back quiet for this period.',
    'signals.notEvaluated': 'Not evaluated, and not counted as clear',
    'signals.score': 'Score',
    'signals.contribution': 'Contribution',
    'signals.weight': 'Weight {percent}',

    // Review sheet ---------------------------------------------------------
    'review.title': 'Record a decision',
    'review.lede': '{company}. The current standing is {status}.',
    'review.appendedTitle': 'This is appended, not edited',
    'review.appendedNote':
      'The previous standing stays on the record and the new one is linked to it.',
    'review.action': 'Action',
    'review.auditor': 'Auditor',
    'review.submit': 'Record decision',
    'review.tonnage': 'Corrected tonnage established',
    'review.tonnagePlaceholder': 'Leave empty if nothing was added',
    'review.tonnageNote':
      'Carried into the impact figures as confirmed, separately from what was projected.',
    'review.notes': 'Notes',
    'review.notesPlaceholder': 'What was checked, and what it showed',
    'review.note.MARKED_FOR_INSPECTION': 'Adds the company to the field schedule.',
    'review.note.UNDER_REVIEW': 'Desk review has started, no site visit yet.',
    'review.note.INFORMATION_REQUESTED':
      'Waiting on the company for records that would settle the question.',
    'review.note.INSPECTION_COMPLETED':
      'Closes the case. Record the corrected tonnage if one was established.',
    'review.note.NO_ACTION_REQUIRED': 'Closes the case with the declaration accepted.',

    // Data quality ---------------------------------------------------------
    'quality.eyebrow': 'Evidence',
    'quality.title': 'Data quality',
    'quality.mean': 'Mean data quality',
    'quality.meanNote': 'across {count} scored companies',
    'quality.complete': 'Complete records',
    'quality.completeNote': 'every field present',
    'quality.thin': 'Thin evidence',
    'quality.thinNote': 'below 50% completeness',
    'quality.notRun': 'Checks not run',
    'quality.notRunNote': 'held out of the calculation',
    'quality.byField': 'Coverage by field',
    'quality.fieldBreakdown': '{available} available, {partial} partial, {missing} missing',
    'quality.couldNotRun': 'Checks that could not run',
    'quality.evaluated': 'Evaluated',
    'quality.unavailable': 'Not run',
    'quality.firing': 'Firing',
    'quality.commonReason': 'Most common reason',
    'quality.ranForEvery': 'Ran for every company',
    'quality.weakest': 'Weakest records',
    'quality.shown': '{shown} of {total} shown, weakest first',
    'quality.quality': 'Quality',
    'quality.checksNotRun': 'Checks not run',
    'quality.columnOrder': 'Columns follow the order of the coverage list above.',

    // Climate impact -------------------------------------------------------
    'impact.eyebrow': 'COP31',
    'impact.title': 'Climate impact',
    'impact.pilotLink': 'Antalya pilot',
    'impact.identified': 'Identified',
    'impact.identifiedNote': 'across {count} flagged companies',
    'impact.confirmed': 'Confirmed by inspection',
    'impact.confirmedNote': '{count} inspections closed',
    'impact.recovered': 'Contribution recovered',
    'impact.recoveredNote': '{value} identified but not yet confirmed',
    'impact.emissions': 'Emissions avoided',
    'impact.emissionsNote': 'against disposal of the same material',
    'impact.chain': 'Impact chain',
    'impact.byProvince': 'Identified tonnage by province',
    'impact.provincesCovered': 'Provinces covered',
    'impact.sectorsCovered': 'Sectors covered',
    'impact.recordsCorrected': 'Records corrected after inspection',
    'impact.byMaterial': 'By material',
    'impact.share': 'Share',
    'impact.contributionAtTariff': 'Contribution at the 2026 tariff',
    'impact.notPricedByWeight': 'not priced by weight',
    'impact.notPricedByWeightNote':
      'Wood packaging is charged per unit rather than per kilogram, so a tonnage '
      + 'cannot be converted into a contribution. The tonnage is shown; the amount is not '
      + 'estimated.',
    'impact.co2eAvoided': 'CO2e avoided',
    'impact.collectors': 'Collector formalisation',
    'impact.collectorsNote':
      'A share of the contribution recovered through inspection funds the move of informal collectors into insured work. Better field coverage then feeds the next round of inspections.',
    'impact.collectorsSupported': 'Collectors supported',
    'impact.movedToFormal': 'Moved to formal work',
    'impact.insuredDays': 'Insured working days',
    'impact.funding': 'Programme funding',
    'impact.fundingNote': 'allocated across {count} districts',
    'impact.fromClosed': 'From closed inspections',
    'impact.fromClosedNote': '{years} insured worker years at {cost} each',
    'impact.ifClosed': 'If the open cases close',
    'impact.ifClosedNote': 'a further {years} worker years, not yet recovered',

    // Pilot ----------------------------------------------------------------
    'pilot.eyebrow': 'Pilot',
    'pilot.run': 'Run pilot',
    'pilot.running': 'Running',
    'pilot.ranMessage': '{count} companies shortlisted in {region}',
    'pilot.runRecorded': 'Run recorded',
    'pilot.asConfigured': 'Showing the configuration as it stands',
    'pilot.province': 'Pilot province',
    'pilot.sector': 'Pilot sector',
    'pilot.allSectors': 'All sectors',
    'pilot.shortlistSize': 'Shortlist size',
    'pilot.top': 'Top {count}',
    'pilot.regionOption': '{region} ({count} companies)',
    'pilot.sequence': 'Run sequence',
    'pilot.shortlisted': 'Shortlisted',
    'pilot.shortlistedValue': '{shortlisted} of {analysed}',
    'pilot.shortlistedNote': '{critical} critical, {high} high, {medium} medium',
    'pilot.atStake': 'Contribution at stake',
    'pilot.atStakeNote': '{tonnes} below the expected range',
    'pilot.recovery': 'Recovery potential',
    'pilot.recoveryNote': 'projected from the confirmation rate of closed inspections',
    'pilot.emissions': 'Emissions avoided',
    'pilot.emissionsNote': 'at {percent} mean data quality',
    'pilot.material': 'Material in the shortlist',
    'pilot.co2eIfRecovered': 'CO2e if recovered',
    'pilot.contribution': 'Contribution',
    'pilot.shortlist': 'Shortlist',
    'pilot.unavailableNote': '{count} checks across the shortlist could not run',
    'pilot.showingTop':
      'Showing the top 25 of {total}. The rest carry the same reasons and are in the queue.',

    // Audit trail ----------------------------------------------------------
    'trail.eyebrow': 'Traceability',
    'trail.title': 'Decision log',
    'trail.verify': 'Verify chain',
    'trail.verification': 'Verification',
    'trail.intact': 'Intact',
    'trail.broken': 'Broken',
    'trail.checked': 'Decisions checked',
    'trail.lastVerified': 'Last verified',
    'trail.firstBreak': 'First break',
    'trail.sequence': 'Sequence {n}',
    'trail.headDigest': 'Head digest',
    'trail.onRecord': 'Decisions on record',
    'trail.onRecordNote': 'appended, never edited in place',
    'trail.howLinked': 'How the link is formed',
    'trail.howLinkedNote':
      'The digest covers the company, the auditor, the action, the statuses either side of it, the note and the timestamp, together with the digest of the previous decision.',
    'trail.recent': 'Recent decisions',
    'trail.auditor': 'Auditor',
    'trail.change': 'Change',
    'trail.recorded': 'Recorded',
    'trail.digest': 'Digest',

    // Transparency ---------------------------------------------------------
    'transparency.eyebrow': 'Method',
    'transparency.title': 'How this works',
    'transparency.disclaimer': 'Standing disclaimer',
    'transparency.scope': 'Scope',
    'transparency.does': 'What it does',
    'transparency.doesNot': 'What it does not do',
    'transparency.principles': 'Principles',
    'transparency.engines': 'Engines',
    'transparency.inService': 'In service',
    'transparency.ready': 'Ready',
    'transparency.notAvailable': 'Not available',
    'transparency.expectedRange': 'Expected range',
    'transparency.policy': 'Policy in force',
    'transparency.weights': 'Signal weights',
    'transparency.bands': 'Priority bands',
    'transparency.calculation': 'Calculation',
    'transparency.strongest': 'Weight of the strongest finding',
    'transparency.coverageNeeded': 'Coverage needed for confidence',
    'transparency.rangeFull': 'Range at full data quality',
    'transparency.rangeZero': 'Widening at zero data quality',
    'transparency.eightChecks': 'The eight checks',
    'transparency.code': 'Code',
    'transparency.compares': 'What it compares',
    'transparency.inputs': 'Inputs it needs',
    'transparency.tariff': 'Contribution tariff, {year}',
    'transparency.tariffColumn': 'Tariff',
    'transparency.co2ePerTonne': 'CO2e avoided per tonne recovered',
    'transparency.fieldsRead': 'Fields the score reads',
    'transparency.ofDataQuality': '{percent} of data quality',
    'transparency.decisionLog': 'Decision log',
    'transparency.decisionLogNote': '{count} decisions recorded and {state} as of the last check.',
    'transparency.verifying': 'verifying',
    'transparency.failing': 'failing verification',

    // Company history ------------------------------------------------------
    'history.eyebrow': 'History',
    'history.title': 'History',
    'history.periodsFiled': 'Periods filed',
    'history.belowRange': 'Below range',
    'history.declaredAgainst': 'Declared against expected',
    'history.periodByPeriod': 'Period by period',
    'history.expectedRange': 'Expected range',
    'history.position': 'Position',
    'history.decisions': 'Decisions taken',
    'history.noDecisionTitle': 'No decision recorded yet',
    'history.noDecisionNote':
      'Nothing has been decided on this company since it entered the queue.',
    'history.noVisitTitle': 'No site visit on record',
    'history.noVisitNote':
      'Field evidence is the one input the platform cannot collect on its own.',
    'history.from': 'from {status}, ',

    // Chart ----------------------------------------------------------------
    'chart.alt': 'Declared packaging against the expected range, with output underneath',
    'chart.outputTonnes': 'Output, tonnes',
    'chart.packagingTonnes': 'Packaging, tonnes',
    'chart.declared': 'Declared packaging',
    'chart.expectedBand': 'Expected range at the time',
    'chart.output': 'Production and imports',
    'chart.declaredAt': '{period}: {amount} declared',
    'chart.outputAt': '{period}: {amount} of output',

    // Assistant ------------------------------------------------------------
    'assistant.open': 'Ask the assistant',
    'assistant.close': 'Close the assistant',
    'assistant.title': 'Assistant',
    'assistant.reading': 'Reading {period}',
    'assistant.notConfigured': 'Not configured',
    'assistant.noKeyTitle': 'No API key',
    'assistant.intro':
      "Ask about the queue, a score, or what a check is measuring. Answers come from this period's figures, not from memory.",
    'assistant.placeholder': 'Ask about this period',
    'assistant.disabledPlaceholder': 'Add a Gemini key to enable this',
    'assistant.message': 'Message',
    'assistant.send': 'Send',
    'assistant.restart': 'Start again',
    'assistant.foot': 'Answers are guidance for triage. The decision stays with the auditor.',
  },

  // ------------------------------------------------------------------ tr --
  tr: {
    'lang.switch': 'Dil',
    'lang.en': 'İngilizce',
    'lang.tr': 'Türkçe',

    'brand.sub': 'Denetim önceliklendirme',

    'key.button': 'API anahtarı',
    'key.set': 'Anahtar kullanılıyor',
    'key.title': 'Kararlar API anahtarı istiyor',
    'key.note':
      'Kararlar, yeniden puanlama ve pilot çalıştırma bu anahtarla imzalanır. Anahtar yalnızca bu sekmede tutulur, sekme kapanınca silinir.',
    'key.placeholder': 'X-API-Key değerini yapıştırın',
    'key.save': 'Anahtarı kullan',
    'key.clear': 'Anahtarı unut',
    'key.saved': 'Anahtar bu sekme için kaydedildi.',
    'key.cleared': 'Anahtar silindi.',

    'nav.overview': 'Genel görünüm',
    'nav.queue': 'Denetim kuyruğu',
    'nav.quality': 'Veri kalitesi',
    'nav.impact': 'İklim etkisi',
    'nav.pilot': 'Antalya pilotu',
    'nav.trail': 'Denetim izi',
    'nav.transparency': 'Nasıl çalışır',
    'nav.lightMode': 'Açık tema',
    'nav.darkMode': 'Koyu tema',
    'nav.switchTheme': 'Temayı değiştir',

    'notFound.title': 'Böyle bir sayfa yok',
    'notFound.note': 'Bu adres platformdaki hiçbir sayfayla eşleşmiyor.',
    'notFound.back': 'Genel görünüme dön',

    'state.errorTitle': 'Servis yanıt vermedi',
    'state.errorNote': "API'nin çalıştığını doğrulayın, sonra yeniden deneyin.",
    'state.retry': 'Yeniden dene',
    'state.loading': 'Yükleniyor',

    'common.close': 'Kapat',
    'common.cancel': 'Vazgeç',
    'common.previous': 'Önceki',
    'common.next': 'Sonraki',
    'common.newer': 'Daha yeni',
    'common.older': 'Daha eski',
    'common.clear': 'Temizle',
    'common.detail': 'Ayrıntı',
    'common.notReported': 'Bildirilmemiş',
    'common.on': 'Açık',
    'common.off': 'Kapalı',
    'common.of': '/',
    'common.company': 'Firma',
    'common.sector': 'Sektör',
    'common.region': 'İl',
    'common.priority': 'Öncelik',
    'common.status': 'Durum',
    'common.material': 'Malzeme',
    'common.tonnage': 'Tonaj',
    'common.period': 'Dönem',
    'common.production': 'Üretim',
    'common.imports': 'İthalat',
    'common.declared': 'Beyan edilen',
    'common.check': 'Kontrol',
    'common.system': 'Sistem',
    'common.range': '{from} - {to}',

    // Genel görünüm --------------------------------------------------------
    'overview.eyebrow': '{period} dönemi',
    'overview.title': 'Genel görünüm',
    'overview.rescore': 'Puanlamayı yeniden çalıştır',
    'overview.scoring': 'Puanlanıyor',
    'overview.rescored': '{count} firma {ms} ms içinde yeniden puanlandı',
    'overview.spread': 'Öncelik dağılımı',
    'overview.openQueue': 'Kuyruğu aç',
    'overview.scoredAcross': 'firma, {regions} il ve {sectors} sektörde puanlandı',
    'overview.awaiting': 'Karar bekleyen',
    'overview.awaitingNote': '{progress} sürüyor, {closed} kapandı',
    'overview.noFiling': 'Kayıtta beyan yok',
    'overview.noFilingNote': 'Üretim biliniyor, beyan bilinmiyor',
    'overview.exposure': 'Risk tutarı',
    'overview.tonnageIdentified': 'Tespit edilen tonaj',
    'overview.tonnageIdentifiedNote': 'Beklenen aralığın altında, yüksek ve kritik öncelikte',
    'overview.atStake': 'Risk altındaki katkı payı',
    'overview.atStakeNote': 'Açıklanamayan tonaja 2026 tarifesi uygulandı',
    'overview.concentration': 'Yoğunlaşma',
    'overview.concentrationNote': "bu tutarın ilk 50 firmada olan payı, {value} değerinde",
    'overview.queue': 'Öncelik kuyruğu',
    'overview.allCompanies': 'Tüm {count} firma',
    'overview.coverage': 'Kapsam',
    'overview.fieldCoverage': 'Alan kapsamı',
    'overview.coverageBreakdown': '{available} tam, {partial} kısmi, {missing} eksik',
    'overview.signalsEvaluated': 'Değerlendirilen sinyaller',
    'overview.firing': '{count} tetiklendi',
    'overview.heldOut':
      'Çalıştırılamayan bir kontrol hesaplamanın dışında tutulur; hiçbir zaman geçmiş sayılmaz.',
    'overview.workflow': 'İş akışı',

    // Kuyruk ---------------------------------------------------------------
    'queue.eyebrow': 'Operasyon',
    'queue.title': 'Denetim kuyruğu',
    'queue.search': 'Firma adı veya vergi numarası',
    'queue.searchLabel': 'Firma ara',
    'queue.allPriorities': 'Tüm öncelikler',
    'queue.allSectors': 'Tüm sektörler',
    'queue.allProvinces': 'Tüm iller',
    'queue.anySize': 'Tüm büyüklükler',
    'queue.anyStatus': 'Tüm durumlar',
    'queue.anyEvidence': 'Tüm dayanak düzeyleri',
    'queue.sortOrder': 'Sıralama',
    'queue.sortBy': 'Sırala: {what}',
    'queue.sort.priority': 'öncelik puanı',
    'queue.sort.gap': 'risk altındaki katkı payı',
    'queue.sort.shortfall': 'açıklanamayan tonaj',
    'queue.sort.quality': 'veri kalitesi',
    'queue.sort.name': 'firma adı',
    'queue.evidence.HIGH': 'Güçlü dayanak',
    'queue.evidence.MEDIUM': 'Kısmi dayanak',
    'queue.evidence.LOW': 'Zayıf dayanak',
    'queue.noMatch': 'Eşleşen firma yok',
    'queue.pageRange': '{total} kaydın {from}-{to} arası',
    'queue.pageTotals': 'bu sayfada {tonnes} ve {value} açıklanamıyor',

    // Kuyruk tablosu -------------------------------------------------------
    'table.leadingReason': 'Başlıca gerekçe',
    'table.data': 'Veri',
    'table.action': 'İşlem',
    'table.contributionShare': 'puanın %{percent} kadarı',
    'table.noConcern': 'Hiçbir kontrol uyarı vermedi',
    'table.atStake': '{value} risk altında',
    'table.emptyTitle': 'Bu filtrelerle eşleşen kayıt yok',
    'table.emptyNote': 'Seçimi genişletin veya tüm dönemi görmek için temizleyin.',

    'action.flag': 'Denetime al',
    'action.flagTitle': 'Denetime al — firmayı saha programına ekler',
    'action.flagOn': 'Zaten denetime alınmış',
    'action.flagDone': '{company} saha programına alındı',
    'action.clear': 'Kuyruktan çıkar',
    'action.clearTitle': 'Kuyruktan çıkar — beyanı kabul eder ve firmayı kuyruktan çıkarır',
    'action.clearOn': 'Zaten çıkarılmış, işlem gerekmiyor',
    'action.clearDone': '{company} kuyruktan çıkarıldı',
    'action.note': 'Denetim kuyruğundan: {action}.',
    'action.for': '{action}: {company}',

    // Firma ----------------------------------------------------------------
    'company.backToQueue': 'Denetim kuyruğu',
    'company.rank': 'Sıra {rank} / {total}',
    'company.history': 'Geçmiş',
    'company.record': 'Karar kaydet',
    'company.noResultTitle': '{period} için sonuç yok',
    'company.noResultNote': 'Firmanın bu dönemde puanlanmış bir kaydı bulunmuyor.',
    'company.priority': 'Denetim önceliği',
    'company.result': 'Sonuç',
    'company.evidenceBase': 'Dayanak düzeyi',
    'company.checksRan': 'Çalışan kontroller',
    'company.checksFiring': 'Tetiklenen kontroller',
    'company.scoredAt': 'Puanlandı',
    'company.engine': 'Motor',
    'company.policy': 'Politika',
    'company.declarationFor': '{period} beyanı',
    'company.exports': 'İhracat',
    'company.packagingDeclared': 'Beyan edilen ambalaj',
    'company.materialSplit': 'Beyan edildiği haliyle malzeme dağılımı',
    'company.declaredAgainst': 'Beyan ile beklenen',
    'company.whyPrioritised': 'Bu firma neden önceliklendirildi',
    'company.allChecks': 'Sekiz kontrolün tamamı',
    'company.evidenceHeld': 'Bu firma için tutulan kanıtlar',
    'company.dataQuality': 'Veri kalitesi {percent}',
    'company.lastUpdated': 'Son güncelleme {when}.',
    'company.missingFields': ' Eksik: {fields}.',
    'company.peerGroup': 'Emsal grubu',
    'company.cohort': 'Grup',
    'company.companiesFiled': 'Beyan veren firma',
    'company.thisCompany': 'Bu firma',
    'company.cohortMedian': 'Grup medyanı',
    'company.siteVisits': 'Saha ziyaretleri',
    'company.noVisit': 'Kayıtlı ziyaret yok, bu nedenle saha kontrolü değerlendirilemedi.',
    'company.measuredOnSite': 'sahada {amount} ölçüldü',
    'company.measured': '{amount} ölçüldü',
    'company.customsLines': 'Bu dönemle eşleşen gümrük kalemleri',
    'company.gtip': 'GTİP',
    'company.description': 'Tanım',
    'company.quantity': 'Miktar',
    'company.packagingPerTonne': 'Ton başına ambalaj',
    'company.impliedPackaging': 'İma edilen ambalaj',
    'company.recordedAs': '{status} olarak kaydedildi',

    // Puan ve aralık -------------------------------------------------------
    'score.priority': '{level} öncelik',
    'score.thinEvidence': 'Zayıf bir dayanakla sıralandı. Bu konumu geçici sayın.',
    'score.forReview': 'İnsan incelemesi için sıralandı, yargılanmadı.',
    'score.evidenceCoverage': 'Dayanak kapsamı',
    'score.dataQuality': 'Veri kalitesi',
    'range.declared': 'Beyan edilen',
    'range.expectedRange': 'Beklenen aralık',
    'range.expectedMedian': 'Beklenen medyan',
    'range.unexplained': 'Açıklanamayan',
    'range.atStake': 'Risk altındaki katkı payı',
    'range.declaredTitle': '{amount} beyan edildi',
    'range.shortfallNote': '. Eksiklik, aralığın ortasına göre değil, alt sınırına göre ölçülür.',

    // Sinyaller ------------------------------------------------------------
    'signals.quietTitle': 'Hiçbir kontrol uyarı vermedi',
    'signals.quietNote': 'Bu dönemde değerlendirilebilen her sinyal sessiz kaldı.',
    'signals.notEvaluated': 'Değerlendirilmedi ve temiz sayılmadı',
    'signals.score': 'Puan',
    'signals.contribution': 'Katkı',
    'signals.weight': 'Ağırlık {percent}',

    // Karar formu ----------------------------------------------------------
    'review.title': 'Karar kaydet',
    'review.lede': '{company}. Mevcut durum: {status}.',
    'review.appendedTitle': 'Bu kayıt eklenir, üzerine yazılmaz',
    'review.appendedNote': 'Önceki durum kayıtta kalır ve yenisi ona bağlanır.',
    'review.action': 'İşlem',
    'review.auditor': 'Denetçi',
    'review.submit': 'Kararı kaydet',
    'review.tonnage': 'Tespit edilen düzeltilmiş tonaj',
    'review.tonnagePlaceholder': 'Bir ekleme yapılmadıysa boş bırakın',
    'review.tonnageNote':
      'Etki rakamlarına, öngörülenden ayrı olarak doğrulanmış şekilde işlenir.',
    'review.notes': 'Notlar',
    'review.notesPlaceholder': 'Ne kontrol edildi ve ne gösterdi',
    'review.note.MARKED_FOR_INSPECTION': 'Firmayı saha programına ekler.',
    'review.note.UNDER_REVIEW': 'Masa başı inceleme başladı, henüz saha ziyareti yok.',
    'review.note.INFORMATION_REQUESTED': 'Konuyu netleştirecek kayıtlar için firma bekleniyor.',
    'review.note.INSPECTION_COMPLETED':
      'Dosyayı kapatır. Tespit edildiyse düzeltilmiş tonajı kaydedin.',
    'review.note.NO_ACTION_REQUIRED': 'Beyanı kabul ederek dosyayı kapatır.',

    // Veri kalitesi --------------------------------------------------------
    'quality.eyebrow': 'Kanıt',
    'quality.title': 'Veri kalitesi',
    'quality.mean': 'Ortalama veri kalitesi',
    'quality.meanNote': 'puanlanan {count} firma genelinde',
    'quality.complete': 'Tam kayıtlar',
    'quality.completeNote': 'her alan mevcut',
    'quality.thin': 'Zayıf dayanak',
    'quality.thinNote': '%50 tamlığın altında',
    'quality.notRun': 'Çalıştırılamayan kontroller',
    'quality.notRunNote': 'hesaplamanın dışında tutuldu',
    'quality.byField': 'Alana göre kapsam',
    'quality.fieldBreakdown': '{available} mevcut, {partial} kısmi, {missing} eksik',
    'quality.couldNotRun': 'Çalıştırılamayan kontroller',
    'quality.evaluated': 'Değerlendirildi',
    'quality.unavailable': 'Çalışmadı',
    'quality.firing': 'Tetiklendi',
    'quality.commonReason': 'En sık gerekçe',
    'quality.ranForEvery': 'Her firma için çalıştı',
    'quality.weakest': 'En zayıf kayıtlar',
    'quality.shown': '{total} kayıttan {shown} tanesi, en zayıftan başlayarak',
    'quality.quality': 'Kalite',
    'quality.checksNotRun': 'Çalışmayan kontrol',
    'quality.columnOrder': 'Sütunlar yukarıdaki kapsam listesinin sırasını izler.',

    // İklim etkisi ---------------------------------------------------------
    'impact.eyebrow': 'COP31',
    'impact.title': 'İklim etkisi',
    'impact.pilotLink': 'Antalya pilotu',
    'impact.identified': 'Tespit edilen',
    'impact.identifiedNote': 'işaretlenen {count} firma genelinde',
    'impact.confirmed': 'Denetimle doğrulanan',
    'impact.confirmedNote': '{count} denetim kapandı',
    'impact.recovered': 'Tahsil edilen katkı payı',
    'impact.recoveredNote': '{value} tespit edildi, henüz doğrulanmadı',
    'impact.emissions': 'Önlenen emisyon',
    'impact.emissionsNote': 'aynı malzemenin bertarafına kıyasla',
    'impact.chain': 'Etki zinciri',
    'impact.byProvince': 'İle göre tespit edilen tonaj',
    'impact.provincesCovered': 'Kapsanan il',
    'impact.sectorsCovered': 'Kapsanan sektör',
    'impact.recordsCorrected': 'Denetim sonrası düzeltilen kayıt',
    'impact.byMaterial': 'Malzemeye göre',
    'impact.share': 'Pay',
    'impact.contributionAtTariff': '2026 tarifesine göre katkı payı',
    'impact.notPricedByWeight': 'ağırlıkla fiyatlanmaz',
    'impact.notPricedByWeightNote':
      'Ahşap ambalaj tarifesi kilogram başına değil adet başına belirlenir; bu nedenle '
      + 'tonajdan katkı payı hesaplanamaz. Tonaj gösterilir, tutar tahmin edilmez.',
    'impact.co2eAvoided': 'Önlenen CO2e',
    'impact.collectors': 'Toplayıcıların kayıt altına alınması',
    'impact.collectorsNote':
      'Denetimle tahsil edilen katkı payının bir kısmı, kayıt dışı toplayıcıların sigortalı işe geçişini finanse eder. Artan saha kapsamı da bir sonraki denetim turunu besler.',
    'impact.collectorsSupported': 'Desteklenen toplayıcı',
    'impact.movedToFormal': 'Kayıtlı işe geçen',
    'impact.insuredDays': 'Sigortalı çalışma günü',
    'impact.funding': 'Program finansmanı',
    'impact.fundingNote': '{count} ilçeye dağıtıldı',
    'impact.fromClosed': 'Kapanan denetimlerden',
    'impact.fromClosedNote': 'her biri {cost} olmak üzere {years} sigortalı işçi yılı',
    'impact.ifClosed': 'Açık dosyalar kapanırsa',
    'impact.ifClosedNote': 'henüz tahsil edilmemiş {years} işçi yılı daha',

    // Pilot ----------------------------------------------------------------
    'pilot.eyebrow': 'Pilot',
    'pilot.run': 'Pilotu çalıştır',
    'pilot.running': 'Çalışıyor',
    'pilot.ranMessage': '{region} ilinde {count} firma kısa listeye alındı',
    'pilot.runRecorded': 'Çalıştırma kaydedildi',
    'pilot.asConfigured': 'Yapılandırma mevcut haliyle gösteriliyor',
    'pilot.province': 'Pilot ili',
    'pilot.sector': 'Pilot sektörü',
    'pilot.allSectors': 'Tüm sektörler',
    'pilot.shortlistSize': 'Kısa liste boyutu',
    'pilot.top': 'İlk {count}',
    'pilot.regionOption': '{region} ({count} firma)',
    'pilot.sequence': 'Çalıştırma sırası',
    'pilot.shortlisted': 'Kısa listeye alınan',
    'pilot.shortlistedValue': '{analysed} firmadan {shortlisted}',
    'pilot.shortlistedNote': '{critical} kritik, {high} yüksek, {medium} orta',
    'pilot.atStake': 'Risk altındaki katkı payı',
    'pilot.atStakeNote': 'beklenen aralığın {tonnes} altında',
    'pilot.recovery': 'Geri kazanım potansiyeli',
    'pilot.recoveryNote': 'kapanan denetimlerin doğrulama oranından öngörüldü',
    'pilot.emissions': 'Önlenen emisyon',
    'pilot.emissionsNote': 'ortalama {percent} veri kalitesinde',
    'pilot.material': 'Kısa listedeki malzeme',
    'pilot.co2eIfRecovered': 'Geri kazanılırsa CO2e',
    'pilot.contribution': 'Katkı payı',
    'pilot.shortlist': 'Kısa liste',
    'pilot.unavailableNote': 'Kısa liste genelinde {count} kontrol çalıştırılamadı',
    'pilot.showingTop':
      '{total} kaydın ilk 25 tanesi gösteriliyor. Kalanlar aynı gerekçeleri taşıyor ve kuyrukta.',

    // Denetim izi ----------------------------------------------------------
    'trail.eyebrow': 'İzlenebilirlik',
    'trail.title': 'Karar kaydı',
    'trail.verify': 'Zinciri doğrula',
    'trail.verification': 'Doğrulama',
    'trail.intact': 'Bütün',
    'trail.broken': 'Kırık',
    'trail.checked': 'Doğrulanan karar',
    'trail.lastVerified': 'Son doğrulama',
    'trail.firstBreak': 'İlk kırılma',
    'trail.sequence': 'Sıra {n}',
    'trail.headDigest': 'Baş özeti',
    'trail.onRecord': 'Kayıttaki kararlar',
    'trail.onRecordNote': 'eklenir, yerinde hiç düzenlenmez',
    'trail.howLinked': 'Bağ nasıl kuruluyor',
    'trail.howLinkedNote':
      'Özet; firmayı, denetçiyi, işlemi, işlemin iki yanındaki durumları, notu ve zaman damgasını, bir önceki kararın özetiyle birlikte kapsar.',
    'trail.recent': 'Son kararlar',
    'trail.auditor': 'Denetçi',
    'trail.change': 'Değişiklik',
    'trail.recorded': 'Kaydedildi',
    'trail.digest': 'Özet',

    // Şeffaflık ------------------------------------------------------------
    'transparency.eyebrow': 'Yöntem',
    'transparency.title': 'Nasıl çalışır',
    'transparency.disclaimer': 'Kalıcı uyarı',
    'transparency.scope': 'Kapsam',
    'transparency.does': 'Ne yapar',
    'transparency.doesNot': 'Ne yapmaz',
    'transparency.principles': 'İlkeler',
    'transparency.engines': 'Motorlar',
    'transparency.inService': 'Kullanımda',
    'transparency.ready': 'Hazır',
    'transparency.notAvailable': 'Kullanılamıyor',
    'transparency.expectedRange': 'Beklenen aralık',
    'transparency.policy': 'Yürürlükteki politika',
    'transparency.weights': 'Sinyal ağırlıkları',
    'transparency.bands': 'Öncelik bantları',
    'transparency.calculation': 'Hesaplama',
    'transparency.strongest': 'En güçlü bulgunun ağırlığı',
    'transparency.coverageNeeded': 'Güven için gereken kapsam',
    'transparency.rangeFull': 'Tam veri kalitesinde aralık',
    'transparency.rangeZero': 'Sıfır veri kalitesinde genişleme',
    'transparency.eightChecks': 'Sekiz kontrol',
    'transparency.code': 'Kod',
    'transparency.compares': 'Neyi karşılaştırır',
    'transparency.inputs': 'İhtiyaç duyduğu girdiler',
    'transparency.tariff': 'Katkı payı tarifesi, {year}',
    'transparency.tariffColumn': 'Tarife',
    'transparency.co2ePerTonne': 'Geri kazanılan ton başına önlenen CO2e',
    'transparency.fieldsRead': 'Puanın okuduğu alanlar',
    'transparency.ofDataQuality': 'veri kalitesinin {percent} kadarı',
    'transparency.decisionLog': 'Karar kaydı',
    'transparency.decisionLogNote':
      'Son kontrole göre {count} karar kayıtlı ve zincir {state}.',
    'transparency.verifying': 'doğrulanıyor',
    'transparency.failing': 'doğrulamada başarısız',

    // Firma geçmişi --------------------------------------------------------
    'history.eyebrow': 'Geçmiş',
    'history.title': 'Geçmiş',
    'history.periodsFiled': 'Beyan verilen dönem',
    'history.belowRange': 'Aralığın altında',
    'history.declaredAgainst': 'Beyan ile beklenen',
    'history.periodByPeriod': 'Dönem dönem',
    'history.expectedRange': 'Beklenen aralık',
    'history.position': 'Konum',
    'history.decisions': 'Alınan kararlar',
    'history.noDecisionTitle': 'Henüz karar kaydedilmedi',
    'history.noDecisionNote': 'Bu firma kuyruğa girdiğinden beri hakkında bir karar verilmedi.',
    'history.noVisitTitle': 'Kayıtlı saha ziyareti yok',
    'history.noVisitNote': 'Saha kanıtı, platformun kendi başına toplayamadığı tek girdidir.',
    'history.from': '{status} durumundan, ',

    // Grafik ---------------------------------------------------------------
    'chart.alt': 'Beklenen aralığa karşı beyan edilen ambalaj, altında üretim',
    'chart.outputTonnes': 'Üretim, ton',
    'chart.packagingTonnes': 'Ambalaj, ton',
    'chart.declared': 'Beyan edilen ambalaj',
    'chart.expectedBand': 'O dönemki beklenen aralık',
    'chart.output': 'Üretim ve ithalat',
    'chart.declaredAt': '{period}: {amount} beyan edildi',
    'chart.outputAt': '{period}: {amount} üretim',

    // Asistan --------------------------------------------------------------
    'assistant.open': 'Asistana sor',
    'assistant.close': 'Asistanı kapat',
    'assistant.title': 'Asistan',
    'assistant.reading': '{period} okunuyor',
    'assistant.notConfigured': 'Yapılandırılmadı',
    'assistant.noKeyTitle': 'API anahtarı yok',
    'assistant.intro':
      'Kuyruk, bir puan veya bir kontrolün neyi ölçtüğü hakkında soru sorun. Yanıtlar bu dönemin rakamlarından gelir, hafızadan değil.',
    'assistant.placeholder': 'Bu dönem hakkında sorun',
    'assistant.disabledPlaceholder': 'Etkinleştirmek için Gemini anahtarı ekleyin',
    'assistant.message': 'Mesaj',
    'assistant.send': 'Gönder',
    'assistant.restart': 'Baştan başla',
    'assistant.foot': 'Yanıtlar triyaj için yol göstericidir. Karar denetçiye aittir.',
  },
};
